services:
  - type: web
    name: israelis-nl
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /elect
        destination: /elect/index.html
      - type: rewrite
        source: /elect/*
        destination: /elect/index.html
      - type: rewrite
        source: /*
        destination: /index.html
